### ISSUE TITLE
Redirect to the docs site from https://pr.omethe.us/pyked

### ISSUE THREAD

**Issue by bryanwweber** [pr-omethe-us/PyKED#100]
https://stackoverflow.com/questions/9082499/custom-domain-for-github-project-pages/9123911#9123911

**Comment by bryanwweber** [comment]
Also https://help.github.com/articles/using-a-custom-domain-with-github-pages/

**Comment by bryanwweber** [comment]
Also, just noticed, Issue #100! Woo!

**Comment by bryanwweber** [comment]
Or maybe just add a link to the homepage?

**Comment by kyleniemeyer** [comment]
I could pretty easily redirect something like https://pyked.pr.ometheus.com, I think; the host allows me to create subdomains, and those are easy to redirect.

**Comment by kyleniemeyer** [comment]
Nvm, that was actually pretty easy... try https://pr.omethe.us/pyked now!

**Comment by kyleniemeyer** [comment]
I did this via a "meta refresh": `<meta http-equiv="refresh" content="0; url=https://pr-omethe-us.github.io/PyKED/">`

**Comment by bryanwweber** [comment]
Nice! Any idea whether the meta-refresh is preferred over setting the domain parameters? I barely understand any of this so I have no idea

**Comment by kyleniemeyer** [comment]
So, if you make the change at the domain level (i.e., with the website host), I think a redirect would happen before the browser even sees the HTML of the page (which is where the meta-refresh happens).

But I think I can only do a domain-level redirect for a subdomain.

**Comment by bryanwweber** [comment]
Ah, now I remember what I was thinking here. In this answer: https://stackoverflow.com/a/22374542/2449192 it is possible to redirect and respect the paths, so https://pr.oemthe.us would redirect to https://pr-oemethe-us.github.io and https://pr.oemthe.us/PyKED would redirect to https://pr-oemethe-us.github.io/PyKED and so forth. But obviously, that's not necessary and this solution seems perfect! Now we just need some content for the homepage 😄
