### ISSUE TITLE
How to handle YAML imports

### ISSUE THREAD

**Issue by bryanwweber** [pr-omethe-us/PyKED#38]
PyYAML is back from the dead, so let's figure out the best way to handle the YAML parsing libraries. There are three options:

1. PyYAML (the "official" implementation, slightly outdated, but back from the dead)
2. ruamel.yaml (the updated implementation)
3. ruamel_yaml (conda-only package of the updated ruamel library)

It would be nice to pick one and standardize on it. We have chosen ruamel.yaml so far, but there is apparently a bug with it and pylint found in this build failure: https://travis-ci.org/pr-omethe-us/PyKED/jobs/205693652

So I propose we switch to PyYAML for a few reasons

1. The build failure
2. PyYAML isn't dead anymore
3. Confusion between `ruamel_yaml` and `ruamel.yaml`
4. PyYAML is the "official" implementation

An alternate option (that I also like in principle but maybe not in practice) is to support whatever version of the YAML library the user already has installed and install PyYAML if nothing is already installed. This might be a touch difficult on the install side, but the import side should be pretty easy, just `try` the import until one succeeds a la conda: https://github.com/conda/conda/blob/master/conda/common/yaml.py

**Comment by kyleniemeyer** [comment]
Yeah, I agree—PyYAML seems the right choice forward.
