### ISSUE TITLE
Should compressed temperature & pressure for RCM data be included in the schema?

### ISSUE THREAD

**Issue by bryanwweber** [pr-omethe-us/PyKED#56]
### PyKED/ChemKED version
v0.1.5

In v0.1.5, there is no facility to include the end-of-compression (also called top-dead-center) conditions from an RCM experiment. Including them would be useful, because it would allow the data to be loaded and plotted very easily, similar to how shock tube data is done now.

One concern is that the compressed temperature is a computed quantity, and as such, depends on the thermodynamic data used for the species. In my experience, the thermo data for stable species tends to be pretty consistent, so there are only small differences in calculated temperature (provided that reactions are disabled). Nonetheless, it is a concern.

**Comment by kyleniemeyer** [comment]
Yup, agree that we should include this, particularly for plotting purposes (may not be needed to simulate an experiment, but could provide a good check).

Would the computed uncertainty in (e.g.) temperature be something that people do/could report?

**Comment by bryanwweber** [comment]
Sure, I have code that estimates the uncertainty, and other people have looked into it as well. I don't have the references off the top of my head though...

**Comment by kyleniemeyer** [comment]
Awesome, then I think we could definitely include these details.
