### ISSUE TITLE
Should the file-author be allowed to have multiple authors?

### ISSUE THREAD

**Issue by bryanwweber** [pr-omethe-us/PyKED#57]
### PyKED/ChemKED version
v0.1.5

Title question raised by Mike Burke's group at Columbia.

**Comment by bryanwweber** [comment]
This seems fine to me. It could be the same format as the `authors` entry in the reference. The field name should also probably be changed to `file-authors`, if we make this change.

My only objection is that all the existing files will probably have to be rewritten to accommodate this.

**Comment by kyleniemeyer** [comment]
yeah, definitely. It should be possible to have a list here, just like with the `reference` `authors`.
