### ISSUE TITLE
Should common-properties be automatically filled into a datapoint element if unspecified?

### ISSUE THREAD

**Issue by bryanwweber** [pr-omethe-us/PyKED#59]
### PyKED/ChemKED version
v0.1.5

Title question raised by Mike Burke's group at Columbia

**Comment by bryanwweber** [comment]
In my opinion, explicit is better than implicit, so I think it should be specified in each datapoint element. This also avoids the case where the user forgets that the temperature is different for one or a few cases, and the wrong value gets included from common properties. Other thoughts?

**Comment by kyleniemeyer** [comment]
I agree. This sort of thing might seem like a timesaver when writing files manually, but that isn't the eventual goal anyways, and I think the potential negatives outweigh the (minor) benefits.
