### ISSUE TITLE
We're still releasing universal (i.e. py2k and py3k) wheels

### ISSUE THREAD

**Issue by bryanwweber** [pr-omethe-us/PyKED#65]
Whoops. As of d21808c38f4925bacce681b245dd2ad95e0758af Python 2 is no longer supported

**Comment by kyleniemeyer** [comment]
Oh. yeah. we should probably clean that up.

**Comment by bryanwweber** [comment]
This is resolved in 850f75792495af4b491d48fa151a3e2db9ba00db
