### ISSUE TITLE
How can we include RCM parameters sensibly?

### ISSUE THREAD

**Issue by bryanwweber** [pr-omethe-us/PyKED#91]
After discussions with Scott and Stephen, we have determined that we need to add several RCM experimental parameters to the ChemKED file as optional fields. We need to determine:

a) what those fields are
b) where they should go
c) how to make them machine readable

We also need to determine what fields belong in a general experimental database, and what belongs in an individual ChemKED file.

**Comment by bryanwweber** [comment]
I think we settled on

1) creating a new `rcm-data` field in a `datapoints` element
2) Adding or moving `compressed-temperature`, `compressed-pressure`, `compression-time`, `compression-ratio`, `stroke`,  and `clearance` as subfields of the `rcm-data` field
3) All other related fields will be specified in the (eventual) experimental apparatus database.

**Comment by bryanwweber** [comment]
We also changed the `volume-history` field to be `time-histories`, and will allow the specification of `pressure`, `volume`, `piston position`, `light emission`, `OH emission`, and `absorption` as the types.

**Comment by bryanwweber** [comment]
Attached to this comment is the template we're using for the RCM characterization initiative, for reference.
[template-chemked.txt](https://github.com/pr-omethe-us/PyKED/files/1424378/template-chemked.txt)

**Comment by kyleniemeyer** [comment]
We should also expand this to a `pressure` time history for shock tubes.

**Comment by bryanwweber** [comment]
I think the `time-histories` field is broad enough to be used for shock tubes as well.
